(()=>{'use strict';
const M=FirstRuckModel,C=FirstRuckScreens,E=RuckExperience,root=document.querySelector('#screen');
const IS_WEB=document.body.classList.contains('web-app'),asset=n=>IS_WEB?document.body.dataset.assetBase+n:'assets/'+n,Storage=window.RuckStorage;let liveRoutes=[],searchCenter=null;
const state=M.createEmptyState();let page='welcome',step=0,routeReturn='ready',record=null,watch=null,lastPoint=null,photo=null,finished=null,feel='Good',journal=[],photos=new Map();
try{const saved=JSON.parse(localStorage.getItem('firstruck-experience-answers')||'null');if(saved&&typeof saved==='object')for(const key of M.ANSWER_KEYS)if(Object.hasOwn(saved,key))state.answers[key]=saved[key];const j=JSON.parse(localStorage.getItem('firstruck-field-journal')||'[]');if(Array.isArray(j))journal=j.filter(x=>x&&typeof x.id==='string'&&Number.isFinite(x.seconds)&&Number.isFinite(x.meters)).slice(0,100);}catch{}
const $=(s)=>root.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kip=(cls='mascot')=>`<img class="${cls}" src="${asset('kip-wombat-cutout.png')}" alt="Kip, a friendly wombat with an orange backpack">`;
const photoAsset=n=>IS_WEB?document.body.dataset.assetBase+n:`../brand/assets/photography/${n}`;
const action=(label,id='next',secondary='')=>`<footer class="actions"><button class="primary" id="${id}">${label}<span class="arrow" aria-hidden="true">↗</span></button>${secondary}</footer>`;
const top=(chapter='')=>`<header class="topline"><button class="back" id="back" aria-label="Go back">←</button><span>${esc(chapter)}</span><span class="mini-brand">FirstRuck</span></header>`;
const progress=()=>`<div class="progress" role="progressbar" aria-label="Onboarding progress" aria-valuemin="0" aria-valuemax="${E.flow.length}" aria-valuenow="${step+1}"><span style="width:${(step+1)/E.flow.length*100}%"></span></div>`;
const note=q=>`<div class="kip-note">${kip('')}<p>${esc(q)}</p></div>`;
function map(){if(selected()?.isDemo===false)return '<div id="live-map" class="live-map" aria-label="Map of selected walking route"></div>';return `<div class="route-map"><svg viewBox="0 0 340 245" role="img" aria-label="Illustrative loop, not a navigable map"><rect width="340" height="245" fill="#e3e8d7"/><g fill="none" stroke="#ced8be" stroke-width="1.3"><path d="M-20 18Q140 120 360 5M-20 35Q140 137 360 22M-20 52Q140 154 360 39M-20 69Q140 171 360 56M-20 86Q140 188 360 73M-20 103Q140 205 360 90M-20 120Q140 222 360 107M-20 137Q140 239 360 124M-20 154Q140 256 360 141M-20 171Q140 273 360 158M-20 188Q140 290 360 175"/></g><path d="M-10 207C55 159 59 104 121 137S232 165 355 77" fill="none" stroke="#b9cfc9" stroke-width="13"/><path d="M-10 27L150 53L195 241M23 251L52 112L340 40" fill="none" stroke="#f9f6ea" stroke-width="11"/><path d="M80 182C63 156 95 116 120 100S145 44 191 51S272 88 262 118S204 139 181 157S124 213 80 182Z" fill="none" stroke="#fffcf4" stroke-width="9"/><path class="route-line" d="M80 182C63 156 95 116 120 100S145 44 191 51S272 88 262 118S204 139 181 157S124 213 80 182Z" fill="none" stroke="#d54a0c" stroke-width="4" stroke-linecap="round"/><circle class="pin" cx="80" cy="182" r="9" fill="#14331d" stroke="#f9f3e6" stroke-width="4"/><g font-size="8" fill="#66785c" font-family="sans-serif"><text x="211" y="199">PARKLAND</text><text x="27" y="70">GREENWAY</text></g></svg><span class="map-label">ILLUSTRATIVE MAP · DEMO ROUTE</span></div>`;}
function nav(active){const icons={today:'<path d="m3 11 9-8 9 8v10H3Z"/><path d="M9 21v-7h6v7"/>',routes:'<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/>',journal:'<path d="M4 3h14a2 2 0 0 1 2 2v16H6a2 2 0 0 1-2-2Z"/><path d="M8 3v18M11 8h5M11 12h5"/>',journey:'<path d="M5 21v-4c0-5 14-3 14-8V3"/><circle cx="5" cy="4" r="2"/><path d="m15 6 4-3 3 4"/>'};return `<nav class="bottom-nav" aria-label="App navigation">${Object.entries(icons).map(([key,v])=>`<button data-app="${key}" ${active===key?'aria-current="page"':''}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${v}</svg>${key[0].toUpperCase()+key.slice(1)}</button>`).join('')}</nav>`;}
function frame(body,footer='',chapter='',cls=''){return `<div class="screen-frame ${cls}">${top(chapter)}${E.flow.some(s=>s.id===page)?progress():''}<section class="content">${body}</section>${footer}</div>`;}
function appframe(body,active){return `<div class="screen-frame ${active}"><header class="app-header"><span class="mini-brand">FirstRuck</span>${kip('avatar')}</header><section class="content">${body}</section>${nav(active)}</div>`;}
function safeUrl(value){try{const url=new URL(String(value));return url.protocol==='https:'?url.href:'';}catch{return '';}}
function discoveryDetails(route){if(route?.discoveryMode!=='gemini-search')return '';const meters=Number(route.distanceFromSearchMeters),distance=Number.isFinite(meters)?`<p class="route-start">Mapped start is about ${meters<1609?`${Math.max(1,Math.round(meters/100)*100)} m`:`${(meters/1609.344).toFixed(1)} mi`} from your search center.</p>`:'';const sources=Array.isArray(route.discoverySources)?route.discoverySources.map(source=>{const url=safeUrl(source?.url);return url?`<li><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(source?.title||'Walking source')} ↗</a></li>`:'';}).join(''):'';return `<aside class="discovery-details"><p class="badge">FOUND WITH GROUNDED WEB SEARCH</p>${distance}<p>Gemini suggested the named area; Geoapify calculated this nearby walking candidate. It may not follow an official named trail.</p>${sources?`<details><summary>Sources Gemini used</summary><ul>${sources}</ul></details>`:''}</aside>`;}
function plan(){return M.buildPlan({...state,sessionOnly:{safetyBranch:state.sessionOnly.safetyBranch||'prefer-not'}});}function routeList(){return liveRoutes.length?liveRoutes:plan().routes;}function selected(){return liveRoutes.find(r=>r.id===state.selectedDemoRouteId)||plan().selectedRoute;}function persist(){try{localStorage.setItem('firstruck-experience-answers',JSON.stringify(state.answers));}catch{announce('Your answers will stay available until you close this page.');}}
function announce(s){document.querySelector('#status').textContent=s;}
function go(id){page=id;const i=E.flow.findIndex(s=>s.id===id);if(i>=0)step=i;render();root.scrollTop=0;const h=$('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function next(){go(E.flow[Math.min(E.flow.length-1,step+1)].id);}function back(){if(page==='record'&&record){go('today');return;}if(['reflection','share'].includes(page)){go('journal');return;}if(E.flow.some(s=>s.id===page)){go(E.flow[Math.max(0,step-1)].id);}else go('today');}
function bind(id,fn){const el=document.getElementById(id);if(el)el.onclick=fn;}
function choiceGroup(options,field,title='',session=false){const v=session?state.sessionOnly[field]:state.answers[field];return `<fieldset class="choices"><legend>${esc(title||'Choose one')}</legend>${options.map(o=>`<label class="choice"><input type="radio" name="${esc(field)}" value="${esc(o.value)}" ${v===o.value?'checked':''} data-session="${session}"><span>${esc(o.label)}</span></label>`).join('')}</fieldset>`;}
function question(){const s=C.getScreen(page);let body=`<p class="eyebrow">${esc(E.flow[step].chapter)} · YOUR STARTING POINT</p><h1>${esc(s.prompt||s.headline)}</h1>${s.help||s.body?`<p class="lede">${esc(s.help||s.body)}</p>`:''}`;
if(s.kind==='starting-area')body+=`<label class="field-label" for="area">Town, neighborhood, or park</label><input class="field" id="area" autocomplete="address-level-2" maxlength="80" value="${esc(state.answers.locationLabel)}" placeholder="A place you know"><p class="hint">A general area is enough. This preview uses demonstration routes.</p>`;
else if(s.groups)body+=s.groups.map(g=>choiceGroup(g.options,g.field,g.legend)).join('');
else body+=choiceGroup(s.options,s.field,'Choose one',s.sessionOnly===true);
if(s.toggle)body+=`<label class="check"><input type="checkbox" id="secured" ${state.answers.loadSecured?'checked':''}><span>${esc(s.toggle.label)}</span></label>`;
body+='<p id="error" class="error" role="alert"></p>';root.innerHTML=frame(body,action(s.kind==='starting-area'?'Reveal what’s next':'Continue'),'Your first ruck');
root.querySelectorAll('input[type=radio]').forEach(input=>input.onchange=()=>{(input.dataset.session==='true'?state.sessionOnly:state.answers)[input.name]=input.value;liveRoutes=[];Storage?.remove('selected-route').catch(()=>{});persist();});
if($('#secured'))$('#secured').onchange=e=>{state.answers.loadSecured=e.target.checked;persist();};if($('#area'))$('#area').oninput=e=>{state.answers.locationLabel=e.target.value;persist();};
bind('next',()=>{const errors=M.validateScreen(page,state);if(!errors.ok){$('#error').textContent=errors.message;$('#error').tabIndex=-1;$('#error').focus();return;}next();});}
function render(){window.RuckMaps?.remove();const p=plan(),r=selected(),lesson=E.lessons[page];
const review=E.flow.find(s=>s.id===page);document.querySelector('#review-chapter').textContent=review?.chapter||'THE EVERYDAY EXPERIENCE';document.querySelector('#review-title').textContent=lesson?lesson.title.replace('\n',' '):({welcome:'An invitation, not a questionnaire.',plan:'The answers become something useful.',routes:'A reason for every route.',paywall:'Earn the next step.',today:'One clear thing to do today.',record:'The walk comes first.',journal:'Progress you can look back on.',journey:'A companion, not a scoreboard.'}[page]||'A few decisions. A meaningful payoff.');document.querySelector('#review-copy').textContent=lesson?.note||'Working local design preview. Existing starter rules are reused; route examples and membership are clearly labeled.';
if(page==='welcome'){root.innerHTML=`<div class="welcome"><header class="topline"><span class="mini-brand">FirstRuck</span><span>YOUR FIRST MONTH</span></header><div class="hero-copy"><p class="eyebrow">THE OUTSIDE IS CALLING</p><h1>A little weight<br>goes a long way.</h1><p>A first ruck built around you.<br>A little companion along the way.</p></div>${action('Build my first ruck','next','<p class="hint">A few questions, with little discoveries along the way.</p>')}</div>`;bind('next',next);}
else if(lesson){root.innerHTML=frame(`${lesson.photo?`<img class="lesson-photo${page==='pack-lesson'?' pack-fit-photo':''}" src="${photoAsset(lesson.photo)}" alt="${page==='pack-lesson'?'A walker adjusting a compact backpack':'A quiet park path'}">`:kip()}<p class="eyebrow">${lesson.kicker}</p><h1>${esc(lesson.title)}</h1><p class="lede">${lesson.body}</p>${note(lesson.quote)}`,action(lesson.action),'A little field knowledge','lesson');bind('next',next);}
else if(review?.kind==='question')question();
else if(page==='plan'){root.innerHTML=frame(`<p class="eyebrow">MADE FROM YOUR ANSWERS</p><h1>Your first ruck.\nRoom to grow.</h1><p class="lede">${esc(p.goal.headline)}</p>${p.pauseCopy?`<p class="notice">${esc(p.pauseCopy)}</p>`:''}<div class="metrics"><div><strong>${p.durationMinutes}<small> min</small></strong><span>First outing</span></div><div><strong>${p.load.maxAddedLb===0?'0':'0–5'}<small> lb</small></strong><span>Added load ceiling</span></div><div><strong>1</strong><span>Loaded day / week*</span></div></div><ul class="rows">${p.reasons.map((x,i)=>`<li><b>0${i+1} / ${['A manageable start','A pack you can learn','Ground you know'][i]}</b><small>${esc(x)}</small></li>`).join('')}</ul><p class="hint">*Only when appropriate for your preparation and safety answers. These are the existing prototype rules, pending qualified review.</p>${note('“Look at that. A plan with your name on it. Figuratively.”')}`,action('Find a route to match'),'Your first plan');bind('next',()=>{routeReturn='ready';next();});}
else if(page==='routes'){root.innerHTML=frame(`<p class="eyebrow">YOUR KIND OF OUTSIDE</p><h1>A path you can\nmake your own.</h1><p class="lede">${esc(state.answers.locationLabel?`Route character for ${state.answers.locationLabel}`:'Choose the character of your first route')}.</p><button class="text-button" id="search-area">Change search area</button>${map()}<p class="hint">${liveRoutes.length?'Map-derived routes. Check surface, hills, access and current conditions.':'Example routes. Connect maps to search real places and street walks.'}</p>${discoveryDetails(r)}${routeList().map((x,i)=>`<button class="route-option ${r?.id===x.id?'selected':''}" data-route="${x.id}" aria-pressed="${r?.id===x.id}"><span class="badge">${x.isDemo===false?(x.discoveryMode==='gemini-search'?'WEB-DISCOVERED MAP CANDIDATE':x.selectionMode==='gemini'?'GEMINI-RANKED MAP CANDIDATE':'MAP-DERIVED CANDIDATE'):(i===0?'Closest preference match':'Another possibility')+' · DEMO'}</span><strong>${esc(x.name)}</strong><p>${esc(x.terrain)} · ${esc(x.distanceLabel)}</p><p>${esc((x.reasons||[]).join(' '))}</p></button>`).join('')}`,action(r?.isDemo===false?'Use this route candidate':'Use this example route','choose-route'), 'Plan a route');root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{state.selectedDemoRouteId=b.dataset.route;if(Storage&&selected()?.isDemo===false)Storage.put('selected-route',selected()).catch(()=>{});render();});bind('choose-route',()=>go(routeReturn));bind('search-area',editSearchArea);}
else if(page==='ready'){root.innerHTML=frame(`<p class="eyebrow">YOUR FIRST CHAPTER</p><h1>Pack ready.\nPath chosen.</h1><div class="summary-band"><h2>${esc(r?.name||'Choose a familiar path')}</h2><p>${p.durationMinutes} minutes · ${esc(p.load.label)}<br>${r?.isDemo===false?'Map-derived candidate · Conditions unverified':'Demonstration route'}</p></div><ul class="rows"><li><b>Before you leave</b><small>${esc(p.packGuidance)}</small></li><li><b>Underfoot</b><small>${esc(p.footwearNote)}</small></li><li><b>Check the day</b><small>Check access, closures, daylight, weather, and conditions. Bring water and a charged phone.</small></li></ul>${p.pauseCopy?`<p class="notice">${esc(p.pauseCopy)}</p>`:''}${note('“You bring yourself. I’ll bring the moral support.”')}`,action('See what comes next'),'Ready when you are');bind('next',next);}
else if(page==='paywall'){root.innerHTML=frame(`${kip()}<p class="eyebrow">FIRSTRUCK MEMBERSHIP · PREVIEW</p><h1>Make this the\nfirst of many.</h1><p class="lede">${esc(p.goal.headline)} Your ${p.durationMinutes}-minute starting plan is ready.</p><ul class="rows"><li><b>A plan that learns your rhythm</b><small>Reflect after each walk and prepare the next manageable step.</small></li><li><b>A little help out there</b><small>Route planning, recording, and practical check-ins.</small></li><li><b>A story worth keeping</b><small>Your photos, field journal, and milestones with Kip.</small></li></ul><p class="hint">Membership design preview. Pricing, trial eligibility, and App Store checkout are not connected.</p>`,action('Explore the app preview','enter','<button class="text-button" id="keep-plan">Back to my prepared plan</button>'),'Your next chapter','paywall');bind('enter',()=>{try{localStorage.setItem('firstruck-onboarding-complete','1');}catch{}go('today');});bind('keep-plan',()=>go('ready'));}
else if(page==='today'){root.innerHTML=appframe(`<p class="eyebrow">YOUR FIRST CHAPTER</p><h1>A little outside,\njust for you.</h1><img class="today-photo" src="${photoAsset('hero-beginner-greenway.png')}" alt="A walker with a compact backpack on a greenway"><div class="weekline">${['M','T','W','T','F','S','S'].map((d,i)=>`<span>${d}<b class="${i===5?'current':''}">${i===5?'•':'·'}</b></span>`).join('')}</div><p class="badge">${record?'SESSION IN PROGRESS':'YOUR PREPARED SESSION'}</p><h2>${esc(r?.name||'A familiar walk')}</h2><p class="lede">${p.durationMinutes} minutes · ${esc(p.load.label)}<br><span class="hint">${r?.isDemo===false?'Map-derived candidate':'Example route'} · Select recording mode to begin.</span></p>${p.pauseCopy?`<p class="notice">${esc(p.pauseCopy)}</p>`:''}<button class="primary" id="start">${record?'Return to recording':'Get ready to walk'}</button><button class="text-button" id="change-route">Choose another route</button>${note('“No perfect weather required. But do check the forecast.”')}`,'today');bind('start',()=>record?go('record'):startDialog());bind('change-route',()=>{routeReturn='today';go('routes');});}
else if(page==='record')renderRecord();
else if(page==='reflection')renderReflection();
else if(page==='journal'){root.innerHTML=appframe(`<p class="eyebrow">YOUR FIELD JOURNAL</p><h1>${journal.length?'Look where\nyou’ve been.':'Good walks.\nLittle discoveries.'}</h1>${journal.length?journal.map((j,i)=>`<article><p class="badge">${esc(j.date)} · ${j.mode==='demo'?'DEMO SESSION':'RECORDED SESSION'}</p>${photos.has(j.id)?`<img class="journal-photo" src="${photos.get(j.id)}" alt="Your walk memory">`:''}<h2>${esc(j.title)}</h2><p class="lede">${Math.round(j.seconds/60)} min · ${(j.meters/1000).toFixed(2)} km · Felt ${esc(j.feel.toLowerCase())}</p><button class="text-button" data-post="${i}">Make a shareable postcard ↗</button><button class="text-button" data-delete="${i}">Delete entry</button></article>`).join(''):`<div class="empty-journal">${kip()}<p class="lede">Your first entry starts with a walk. Keep a photo, a feeling, or one small thing you noticed.</p><p class="hint">Your journal is private. You choose what leaves it.</p><button class="primary" id="journal-start">Try a demo walk</button></div>`}`,'journal');bind('journal-start',()=>start('demo'));root.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>{finished=journal[Number(b.dataset.post)];go('share');});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const idx=Number(b.dataset.delete);modal('Delete this journal entry?','This removes the saved session from this browser.',[['Delete entry',()=>{Storage?.remove('photo-'+journal[idx].id).catch(()=>{});Storage?.remove('track-'+journal[idx].id).catch(()=>{});photos.delete(journal[idx].id);journal.splice(idx,1);saveJournal();render();}],['Keep entry',()=>{}]]);});}
else if(page==='journey'){root.innerHTML=appframe(`<p class="eyebrow">YOU & KIP</p><h1>Every walk\nadds a chapter.</h1>${kip()}<p class="lede">${journal.length?`${journal.length} ${journal.length===1?'outing':'outings'} in your journal. There is no deadline for the next one.`:'You are at the trailhead. A very good place to begin.'}</p><ul class="rows"><li><b>${journal.length?'✓':'01'} / First steps</b><small>Complete an outing and notice how it felt.</small></li><li><b>02 / A familiar path</b><small>Return to a walk you enjoyed.</small></li><li><b>03 / Your little collection</b><small>Keep a photo or a thought from outside.</small></li></ul><button class="text-button" id="edit-plan">Revisit my starting plan</button><p class="hint">Milestones celebrate showing up. They never require heavier loads or consecutive-day streaks.</p>`,'journey');bind('edit-plan',()=>go('goal'));}
else if(page==='share')renderShare();
bind('back',back);root.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>{if(b.dataset.app==='routes')routeReturn='today';go(b.dataset.app);});if($('#live-map')&&r?.isDemo===false){window.RuckMaps?.draw('live-map',r);if(record?.mode==='gps'&&record.points.length){const point=record.points[record.points.length-1];window.RuckMaps?.updatePosition(point,record.points);}}}
function modal(title,body,buttons){const trigger=document.activeElement;const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(title)}</h2><p>${esc(body)}</p>`;buttons.forEach(([label,fn],i)=>{const b=document.createElement('button');b.className=i===0?'primary':'secondary';b.textContent=label;b.onclick=()=>{d.close();fn();};d.append(b);});d.onclose=()=>{d.remove();if(trigger?.isConnected)trigger.focus();};document.body.append(d);d.showModal();}
function editSearchArea(){const d=document.createElement('dialog');d.innerHTML=`<h2>Where would you like to walk?</h2><p>${IS_WEB?'Find a place or use your current location. Search goes to our mapping provider when connected.':'This review updates your search preference; live lookup is not connected.'}</p><label class="field-label" for="search-place">Town, park, or neighborhood</label><input class="field" id="search-place" autocomplete="address-level-2" maxlength="80" value="${esc(state.answers.locationLabel)}"><button class="primary" id="apply-place">${IS_WEB?'Search this area':'Use this area'}</button><button class="secondary" id="nearby">Use my location</button><div id="place-results"></div><button class="text-button" id="cancel-area">Cancel</button><p id="location-message" role="status"></p>`;document.body.append(d);d.showModal();d.onclose=()=>{d.remove();$('#search-area')?.focus();};const msg=d.querySelector('#location-message');async function fetchRoutes(center){searchCenter=center;msg.textContent='Finding walking candidates…';try{const result=await RuckMaps.routes({...center,minutes:plan().durationMinutes,shape:state.answers.routeShape||'out-back',surface:state.answers.surface||'either',hillComfort:state.answers.hillComfort||'gentle',priority:state.answers.routePriority||state.answers.setting||'repeatability'});if(!d.open)return;if(!result.routes.length){msg.textContent='No route candidates fit this search. Try another starting place. Existing routes have not changed.';return;}liveRoutes=result.routes;state.selectedDemoRouteId=liveRoutes[0].id;state.answers.locationLabel=center.label;if(Storage)Storage.put('selected-route',liveRoutes[0]).catch(()=>{});persist();d.close();render();}catch(e){if(d.open)msg.textContent=e.message;}}
d.querySelector('#apply-place').onclick=async()=>{const text=d.querySelector('#search-place').value.trim();if(!IS_WEB){state.answers.locationLabel=text;persist();d.close();render();return;}await RuckMaps.ready;if(!RuckMaps.enabled()){msg.textContent='Live route search is not available in this build. You can keep using example routes.';return;}msg.textContent='Finding places…';try{const result=await RuckMaps.search(text);if(!d.open)return;const container=d.querySelector('#place-results');container.replaceChildren();result.places.forEach(place=>{const btn=document.createElement('button');btn.className='secondary';btn.textContent=place.label;btn.onclick=()=>fetchRoutes(place);container.append(btn);});msg.textContent=result.places.length?'Choose your starting area.':'No places found. Try a town or nearby landmark.';}catch(e){if(d.open)msg.textContent=e.message;}};d.querySelector('#cancel-area').onclick=()=>d.close();d.querySelector('#nearby').onclick=async()=>{if(IS_WEB){await RuckMaps.ready;if(!RuckMaps.enabled()){msg.textContent='Live route search is not available in this build. Enter a place later or explore example routes.';return;}}if(!navigator.geolocation){msg.textContent='Location is unavailable here. Enter a place instead.';return;}msg.textContent='Finding your location…';navigator.geolocation.getCurrentPosition(pos=>{if(!d.open)return;const center={latitude:pos.coords.latitude,longitude:pos.coords.longitude,label:'Near your current location'};if(IS_WEB)fetchRoutes(center);else{state.answers.locationLabel=center.label;if(Storage)Storage.put('selected-route',liveRoutes[0]).catch(()=>{});persist();d.close();render();}},()=>{if(d.open)msg.textContent='Could not use your location. Enter a place instead.';},{timeout:10000,maximumAge:60000});};}
function startDialog(){if(selected()?.isDemo===false){modal('Ready to follow your route?','Start foreground GPS to place your current location and recorded path over the selected route. Keep this browser open; recording can stop when your screen locks.',[['Start with GPS',()=>start('gps')],['Preview without GPS',()=>start('demo')],['Not yet',()=>{}]]);return;}modal('Ready for a little outside?','Try the complete experience with a demo, or record GPS while this browser stays open. Browser recording can stop when your screen locks. Example routes are not navigation.',[['Try a demo walk',()=>start('demo')],['Record foreground GPS',()=>start('gps')],['Not yet',()=>{}]]);}
function start(mode){if(record){go('record');return;}photo=null;finished=null;lastPoint=null;record={mode,started:performance.now(),accumulated:0,running:true,meters:0,points:[],message:mode==='demo'?'Demo walk · No GPS is being recorded.':'Waiting for a location fix…'};go('record');if(mode==='gps')startGps();}
function startGps(){if(!navigator.geolocation){record.message='Location is unavailable in this browser. End this session or try the demo.';render();return;}watch=navigator.geolocation.watchPosition(pos=>{if(!record||!record.running)return;const point={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,timestamp:pos.timestamp};if(Date.now()-point.timestamp>15000||!E.acceptPoint(lastPoint,point)){record.message='GPS signal is weak. Distance is waiting for a reliable fix.';updateRecord();return;}if(lastPoint)record.meters+=E.distance(lastPoint,point);lastPoint=point;record.points.push(point);record.message='Foreground GPS · Blue shows your current location and recorded path.';window.RuckMaps?.updatePosition(point,record.points);updateRecord();},err=>{if(!record)return;record.message=err.code===1?'Location permission was not granted. No distance is being recorded.':'GPS is unavailable. Distance pauses until the signal returns.';updateRecord();},{enableHighAccuracy:true,maximumAge:0,timeout:15000});}
function stopGps(){if(watch!==null){navigator.geolocation.clearWatch(watch);watch=null;}lastPoint=null;}
function seconds(){return record?Math.floor(E.elapsed(record,performance.now())/1000):0;}function meters(){return record?.mode==='demo'?seconds()*1.05:record?.meters||0;}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function renderRecord(){if(!record){go('today');return;}const r=selected(),liveGuidance=record.mode==='gps'&&r?.isDemo===false;root.innerHTML=frame(`<p class="eyebrow">${record.mode==='demo'?'DEMO WALK':'FOREGROUND RECORDING'}</p><h1>Your time outside.</h1>${record.mode==='demo'?map():(liveGuidance?'<div id="live-map" class="live-map" aria-label="Your current location and recorded path over the selected walking route"></div><div class="notice">Orange is the selected route. Blue is your current location and recorded path. Keep this browser open; background recording is not guaranteed.</div>':`<div class="notice">${IS_WEB?'Your GPS track is saved on this device. Keep this browser open; background recording is not guaranteed.':'Your GPS track stays in memory during this preview.'} No selected live route is available.</div>`)}<p class="record-time" id="timer">${formatTime(seconds())}</p><div class="metrics"><div><strong id="distance">${(meters()/1000).toFixed(2)}</strong><span>km ${record.mode==='demo'?'simulated':''}</span></div><div><strong>${record.running?'On':'Pause'}</strong><span>Recording</span></div><div><strong>${photo?'1':'0'}</strong><span>Moments kept</span></div></div><p class="hint" id="gps-status">${esc(record.message)}</p><div class="record-actions"><button class="secondary" id="pause">${record.running?'Pause':'Resume'}</button><button class="primary" id="finish">Finish walk</button></div><button class="text-button" id="checkin">How’s it feeling? · Check in</button>${photoPicker()}${photo?`<img class="moment-photo" src="${photo}" alt="Your chosen walk photo">`:''}<p class="hint">Stop somewhere comfortable before using your phone.</p>`, '', 'Out on your walk','record');bind('back',back);bind('pause',()=>{if(record.running){record.accumulated=E.elapsed(record,performance.now());record.running=false;stopGps();}else{record.started=performance.now();record.running=true;if(record.mode==='gps')startGps();}render();});bind('finish',finish);bind('checkin',checkin);bindPhoto();}
function updateRecord(){if(page!=='record'||!record)return;$('#timer').textContent=formatTime(seconds());$('#distance').textContent=(meters()/1000).toFixed(2);$('#gps-status').textContent=record.message;}
setInterval(updateRecord,1000);
function checkin(){modal('How does the walk feel?','Choose what fits right now. These check-ins use fixed guidance, not a live AI coach.',[['Comfortable',()=>modal('Keep it comfortable.','Notice your surroundings and keep your pace conversational. There is no need to add distance today.',[['Back to my walk',()=>{}]])],['Pack rubbing or bouncing',()=>modal('Pause and adjust.','Stop somewhere comfortable, check the straps, and adjust or remove the load. End the walk if the problem continues.',[['Back to my walk',()=>{}]])],['Pain, dizziness, or feeling unwell',()=>modal('Stop the walk.','Do not push through concerning symptoms. Seek appropriate medical help; contact local emergency services if symptoms are severe or urgent.',[['Finish this walk',finish],['Keep recording paused',()=>{if(record?.running){record.accumulated=E.elapsed(record,performance.now());record.running=false;stopGps();renderRecord();}}]])],['Close check-in',()=>{}]]);}
function photoPicker(){return '<label class="photo-button">＋ Keep a photo from this walk<input id="photo" type="file" accept="image/*" aria-label="Choose a photo from this walk"></label>';}
function bindPhoto(){const input=$('#photo');if(!input)return;input.onchange=async()=>{const f=input.files[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>20*1024*1024){announce('Choose an image smaller than 20 MB.');return;}const url=URL.createObjectURL(f);try{const im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas');const scale=Math.min(1,1200/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);photo=c.toDataURL('image/jpeg',.87);render();announce('Photo added. Save the journal entry to keep it on this device.');}catch{announce('This image could not be opened. Try a JPEG or PNG.');}finally{URL.revokeObjectURL(url);}};}
function finish(){if(!record)return;finished={id:crypto.randomUUID(),date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}),seconds:seconds(),meters:meters(),mode:record.mode,title:record.mode==='demo'?'A little outside · Demo walk':'A little outside',feel:'Good'};if(Storage){Storage.put('track-'+finished.id,record.points).catch(()=>announce('The track could not be saved on this device.'));Storage.remove('active-recording').catch(()=>{});}stopGps();record=null;feel='Good';if(Storage)Storage.put('pending-reflection',finished).catch(()=>{});go('reflection');}
function renderReflection(){if(!finished){go('journal');return;}root.innerHTML=frame(`<p class="eyebrow">${finished.mode==='demo'?'DEMO WALK COMPLETE':'WALK COMPLETE'}</p><h1>You went outside.\nThat counts.</h1>${kip()}<p class="lede">${formatTime(finished.seconds)} outside · ${(finished.meters/1000).toFixed(2)} km${finished.mode==='demo'?' simulated':''}</p><label class="field-label" for="feeling">How did that feel?</label><select id="feeling">${['Good','Easier than expected','More than enough','Uncomfortable'].map(x=>`<option ${feel===x?'selected':''}>${x}</option>`).join('')}</select><p class="hint">This reflection helps shape your next outing. There is no automatic increase.</p>${photoPicker()}${photo?`<img class="moment-photo" src="${photo}" alt="Your walk memory">`:''}`,action('Save to my field journal','save'),'A moment to reflect');$('#feeling').onchange=e=>{feel=e.target.value;};bindPhoto();bind('save',async()=>{const button=$('#save');if(button){button.disabled=true;button.textContent='Saving your memory…';}finished.feel=feel;try{if(photo){await Storage?.put('photo-'+finished.id,photo);photos.set(finished.id,photo);}if(!journal.some(j=>j.id===finished.id))journal.unshift({...finished});saveJournal();await Storage?.remove('pending-reflection');go('journal');}catch{announce('Your memory could not be saved. Please try again.');if(button){button.disabled=false;button.textContent='Save to my field journal';}}});}
function saveJournal(){try{localStorage.setItem('firstruck-field-journal',JSON.stringify(journal));}catch{announce('Journal storage is full. This entry stays in this tab; export a postcard to keep it.');}}
function renderShare(){const sharePhoto=photos.get(finished?.id);if(!finished){go('journal');return;}root.innerHTML=frame(`<p class="eyebrow">A LITTLE POSTCARD FROM OUTSIDE</p><h1>Keep the feeling.\nShare the moment.</h1><div class="postcard">${sharePhoto?`<img src="${sharePhoto}" alt="Photo included in your postcard">`:kip()}<p class="eyebrow">FIRSTRUCK · FIELD JOURNAL</p><h2>${esc(finished.title)}</h2><p>${Math.round(finished.seconds/60)} minutes outside · ${(finished.meters/1000).toFixed(2)} km${finished.mode==='demo'?' · Demo':''}</p><p class="hint">Make more of your next walk.</p></div><p class="hint">No route, start point, GPS coordinates, or original photo metadata is included. Check the photo itself for anything you would rather keep private.</p><p class="hint">${IS_WEB?'Photos are saved on this device. Download a postcard to keep a separate copy.':'Photos stay in this tab only. Download your postcard to keep the image.'}</p>`,action('Download postcard','download','<button class="secondary" id="share-native">Open share sheet</button>'),'Your choice to share');bind('download',()=>exportPostcard(false));bind('share-native',()=>exportPostcard(true));}
async function exportPostcard(share){try{const c=document.createElement('canvas');c.width=1080;c.height=1350;const ctx=c.getContext('2d');ctx.fillStyle='#14331d';ctx.fillRect(0,0,1080,1350);const im=new Image();im.src=photos.get(finished.id)||asset('kip-wombat-cutout.png');await im.decode();const size=940,scale=Math.max(size/im.width,800/im.height);ctx.save();ctx.beginPath();ctx.rect(70,70,size,800);ctx.clip();ctx.drawImage(im,70+(size-im.width*scale)/2,70+(800-im.height*scale)/2,im.width*scale,im.height*scale);ctx.restore();ctx.fillStyle='#f9f3e6';ctx.font='22px sans-serif';ctx.fillText('FIRSTRUCK / FIELD JOURNAL',70,945);ctx.font='64px Georgia';ctx.fillText('A little outside.',70,1045);ctx.font='28px sans-serif';ctx.fillText(`${Math.round(finished.seconds/60)} minutes · ${(finished.meters/1000).toFixed(2)} km${finished.mode==='demo'?' · DEMO WALK':''}`,70,1110);ctx.font='25px Georgia';ctx.fillText('Make more of your next walk.',70,1240);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('Export failed');const file=new File([blob],'firstruck-postcard.png',{type:'image/png'});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'A little outside with FirstRuck'});return;}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);announce(share?'Sharing is unavailable here. Your postcard has been downloaded.':'Postcard downloaded.');}catch(e){if(e.name!=='AbortError')announce('The postcard could not be exported. Try again.');}}
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{if(b.dataset.jump==='routes')routeReturn='ready';go(b.dataset.jump);});document.querySelector('#restart').onclick=()=>modal('Restart your onboarding?','This clears your onboarding choices. Your saved journal stays available.',[['Restart onboarding',()=>{state.answers=M.createEmptyAnswers();state.sessionOnly={safetyBranch:null};state.selectedDemoRouteId=null;liveRoutes=[];Storage?.remove('selected-route').catch(()=>{});try{localStorage.removeItem('firstruck-onboarding-complete');}catch{}persist();go('welcome');}],['Keep my answers',()=>{}]]);
setInterval(()=>{if(Storage&&record)Storage.put('active-recording',{...record,accumulated:E.elapsed(record,performance.now()),started:0,running:false}).catch(()=>{});},5000);
if(Storage){(async()=>{try{const savedRoute=await Storage.get('selected-route');if(savedRoute?.geometry&&savedRoute.isDemo===false){liveRoutes=[savedRoute];state.selectedDemoRouteId=savedRoute.id;}for(const j of journal){const img=await Storage.get('photo-'+j.id);if(img)photos.set(j.id,img);}const saved=await Storage.get('active-recording');if(saved&&!record&&typeof saved.accumulated==='number'){record={...saved,started:performance.now(),running:false,message:'Recovered session · Paused. Resume when ready.'};}const pending=await Storage.get('pending-reflection');if(pending?.id&&!journal.some(j=>j.id===pending.id)){finished=pending;go('reflection');}else if(localStorage.getItem('firstruck-onboarding-complete')==='1')go('today');}catch{announce('Device storage is unavailable. Export your photos to keep them.');}})();}
window.addEventListener('beforeunload',e=>{if(record){e.preventDefault();e.returnValue='';}});render();
})();
