<?php

declare(strict_types=1);

namespace Yatsn\AI;

/** Provider-neutral launch StyleMaps recovered and refined from V1. */
final class StylePromptCatalog
{
    /** @var array<string, array<string, string>> */
    private const MAPS = [
        'photoreal_cinema' => [
            'style' => 'Premium cinematic realism with an emotionally readable story beat.',
            'medium' => 'Filmic live-action still with restrained high-end digital finishing.',
            'color' => 'Natural skin color, deep neutrals, controlled warm-cool separation, filmic grade.',
            'lighting' => 'Motivated key, fill, and rim light with practical sources, soft bloom, and dimensional shadow.',
            'surface' => 'Believable skin, fabric, metal, wood, glass, water, and atmospheric particulates.',
            'motion' => 'Natural gesture, environmental interaction, fabric movement, weather, and cinematic motion blur.',
            'composition' => 'Story-beat framing, readable silhouettes, layered depth, purposeful negative space.',
            'mood' => 'Emotionally immediate, dramatic, intimate, and credible.',
            'atmosphere' => 'Volumetric air, subtle haze, lens depth, and environmental storytelling.',
            'detail' => 'Refined micro-detail with natural texture; faces remain the sharp emotional focus.',
            'influence' => 'Contemporary narrative cinema, practical lighting, and disciplined editorial photography.',
            'typography' => 'Only original, scene-native lettering when permitted; otherwise none.',
            'special' => 'Filmic dynamic range, subtle halation, gentle grain, realistic lens behavior.',
            'avoid' => 'AI oversharpening, plastic skin, exaggerated gloss, flat studio backdrops, generic posing.',
        ],
        'oil_painting_realism' => [
            'style' => 'Heirloom narrative oil painting with recognizable faces and painterly depth.',
            'medium' => 'Classical oil on linen with layered glazing, controlled impasto, and hand-painted edges.',
            'color' => 'Deep earth pigments, burnished gold, muted jewel tones, and luminous skin.',
            'lighting' => 'Dramatic tenebrist light with warm highlights and deep transparent shadow.',
            'surface' => 'Visible canvas weave, glazed skin, tactile fabric, polished brush passages.',
            'motion' => 'A poised narrative instant with restrained gesture and moving fabric or atmosphere.',
            'composition' => 'Painterly depth, triangular grouping, golden-ratio balance, clear focal hierarchy.',
            'mood' => 'Timeless, intimate, romantic, dignified, and emotionally resonant.',
            'atmosphere' => 'Soft varnished glow, deep spatial shadow, and subtle environmental haze.',
            'detail' => 'Highest detail on faces and hands; looser brushwork toward the edges.',
            'influence' => 'Old-master portrait craft, romantic narrative painting, and museum-quality glazing.',
            'typography' => 'No modern typography; any permitted text must appear as original painted or carved detail.',
            'special' => 'Preserve painterly brush character without losing facial identity.',
            'avoid' => 'Flat CG rendering, synthetic gloss, harsh HDR, photographic cutout faces.',
        ],
        'watercolor' => [
            'style' => 'Luminous transparent watercolor storytelling with delicate emotional clarity.',
            'medium' => 'Layered transparent washes, wet-on-wet blooms, dry-brush accents, granulating pigment.',
            'color' => 'Luminous pastels with a restrained palette and a few saturated focal accents.',
            'lighting' => 'Paper white creates glow; diffuse light and softly bleeding shadows.',
            'surface' => 'Cold-pressed cotton paper, feathered edges, pigment pools, subtle splatter.',
            'motion' => 'Flowing washes, gestural marks, drifting atmosphere, and fluid fabric.',
            'composition' => 'Breathing negative space with a clear subject silhouette and balanced simplicity.',
            'mood' => 'Tender, poetic, hopeful, reflective, and dreamlike.',
            'atmosphere' => 'Mist-like washes and transparent environmental layers.',
            'detail' => 'Crisp selective facial marks surrounded by softer suggestive passages.',
            'influence' => 'Traditional watercolor craft and contemporary narrative illustration.',
            'typography' => 'Original hand-painted lettering only when permitted and compositionally justified.',
            'special' => 'Let untouched paper participate in the light and emotional rhythm.',
            'avoid' => 'Opaque acrylic appearance, uniform digital sharpness, muddy overworking, heavy outlines.',
        ],
        'impressionist_painting' => [
            'style' => 'Impressionist light shaped around a recognizable, emotionally legible human moment.',
            'medium' => 'Broken color, visible brushwork, optical mixing, and plein-air immediacy.',
            'color' => 'Pastel vibrancy, complementary shadow color, warm natural highlights.',
            'lighting' => 'Light is the organizing subject: sun diffusion, reflected color, flickering atmosphere.',
            'surface' => 'Canvas weave, varied paint thickness, lively directional brush marks.',
            'motion' => 'Momentary gesture, moving air, water, foliage, fabric, and changing light.',
            'composition' => 'An observed instant with asymmetrical balance and a strong focal rhythm.',
            'mood' => 'Romantic, immediate, nostalgic, joyful, or quietly contemplative.',
            'atmosphere' => 'Colored air and luminous distance rather than hard-edged realism.',
            'detail' => 'Faces remain identifiable through selective structure amid loose paint.',
            'influence' => 'Nineteenth-century impressionist color practice and modern cinematic staging.',
            'typography' => 'No text unless original painted lettering is explicitly permitted.',
            'special' => 'Preserve identity with economical facial structure, not photographic cutout detail.',
            'avoid' => 'Hard outlines, digital crispness, uniform detail, grey or muddy shadows.',
        ],
        'art_deco' => [
            'style' => 'Art Deco elegance translated into an original cinematic world.',
            'medium' => 'Lacquered illustration, geometric ornament, polished enamel, gold and chrome accents.',
            'color' => 'Onyx, ivory, champagne, emerald, burgundy, and restrained metallic gold.',
            'lighting' => 'Glamorous rim light, mirrored gleam, luminous stepped architectural accents.',
            'surface' => 'Polished stone, velvet, glass, enamel, brushed metal, pristine inlay.',
            'motion' => 'Poised gestures, sweeping arcs, fan motifs, and elegant directional rhythm.',
            'composition' => 'Controlled symmetry, stepped geometry, elongated verticals, monumental framing.',
            'mood' => 'Sophisticated, celebratory, romantic, luxurious, and assured.',
            'atmosphere' => 'Theatrical glamour with clean architectural depth and soft haze.',
            'detail' => 'Precise ornament supports rather than overwhelms the protagonists.',
            'influence' => 'Interwar decorative arts, streamlined architecture, and luxury poster craft.',
            'typography' => 'Original geometric lettering only when permitted; never song or artist branding.',
            'special' => 'Keep faces natural and recognizable inside the stylized geometry.',
            'avoid' => 'Rust, casual grunge, clutter, copied poster layouts, or existing trademarks.',
        ],
        'indie_pop_pastel' => [
            'style' => 'Contemporary indie pastel dream with intimate human warmth.',
            'medium' => 'Soft digital paint blended with understated analog-photo grain.',
            'color' => 'Cream, rose, mint, sky blue, peach, lavender, and gentle neutral shadows.',
            'lighting' => 'Diffuse window or late-afternoon glow with soft bloom and delicate backlight.',
            'surface' => 'Matte paper, soft fabric, subtle grain, translucent highlights.',
            'motion' => 'Small natural gestures, breeze, drifting curtains, bokeh, and suspended moments.',
            'composition' => 'Balanced off-center people, intimate distance, generous breathing room.',
            'mood' => 'Affectionate, wistful, hopeful, youthful, and sincere.',
            'atmosphere' => 'Hazy everyday magic with tactile, lived-in details.',
            'detail' => 'Natural recognizable faces; soft peripheral detail and gentle edges.',
            'influence' => 'Independent editorial photography, pastel illustration, and handmade album-era craft without copying artwork.',
            'typography' => 'Small original hand-made text only when permitted; otherwise none.',
            'special' => 'Favor emotional authenticity over polish or spectacle.',
            'avoid' => 'Harsh contrast, HDR sharpness, commercial stock-photo poses, plastic skin.',
        ],
        'jazz_expressionism' => [
            'style' => 'Midnight jazz expressionism driven by rhythm, gesture, and smoky light.',
            'medium' => 'Brush ink, gouache, pastel smudge, and layered poster-print texture.',
            'color' => 'Indigo, ochre, cream, tobacco brown, brass, and selective crimson.',
            'lighting' => 'Focused club spotlight through smoke with pools of deep shadow.',
            'surface' => 'Paper grain, dry brush, rubbed pastel, ink bleed, worn stage materials.',
            'motion' => 'Loose gestural rhythm, syncopated diagonals, expressive hands and fabric.',
            'composition' => 'Dynamic diagonal movement with an intimate focal pocket around the protagonists.',
            'mood' => 'Soulful, nocturnal, sophisticated, improvisational, and emotionally charged.',
            'atmosphere' => 'Smoke, dust, warm practical light, and compressed late-night space.',
            'detail' => 'Faces resolve clearly within energetic surrounding marks.',
            'influence' => 'Mid-century jazz print design, expressionist brushwork, and documentary club photography.',
            'typography' => 'No existing music branding; original abstract marks only when text is permitted.',
            'special' => 'Let visual rhythm echo musical phrasing without showing a specific performer.',
            'avoid' => 'Rigid geometry, sterile realism, famous musician likenesses, copied record sleeves.',
        ],
        'psychedelic_rock' => [
            'style' => 'Psychedelic reverie with vivid optical energy and a readable human center.',
            'medium' => 'Layered silkscreen color, liquid illustration, halftone, and hand-inked contours.',
            'color' => 'Acid magenta, orange, cyan, lime, violet, and deep grounding darks.',
            'lighting' => 'Flat radiance, aura glows, color vibration, prismatic edge light.',
            'surface' => 'Matte ink, paper tooth, registration shifts, controlled ink bleed.',
            'motion' => 'Spirals, melting transitions, kaleidoscopic drift, flowing hair and fabric.',
            'composition' => 'Iconic central energy with layered depth and a clear protagonist silhouette.',
            'mood' => 'Ecstatic, expansive, strange, playful, and emotionally immersive.',
            'atmosphere' => 'Color fields and organic motifs transform the environment without obscuring faces.',
            'detail' => 'Intricate supporting patterns; identities remain clean and separable.',
            'influence' => '1960s screen-print craft, optical art, liquid-light projection, and surreal illustration.',
            'typography' => 'No lettering unless original non-lyric text is explicitly permitted.',
            'special' => 'Keep the scene legible beneath the optical complexity.',
            'avoid' => 'Copied concert posters, existing iconography, illegible clutter, muddy color.',
        ],
        'punk_collage' => [
            'style' => 'Raw punk zine collage built around authorized protagonist portraits.',
            'medium' => 'Photocopy grain, torn paper, scissors, tape, staples, marker, and rough screenprint.',
            'color' => 'High-contrast black and white with one controlled spot color, usually red.',
            'lighting' => 'Harsh flash, crushed blacks, xerox glare, and abrupt tonal breaks.',
            'surface' => 'Folded paper, ripped edges, adhesive marks, overprint, concrete, and ink noise.',
            'motion' => 'Tilted fragments, cutout action, explosive diagonals, and imperfect registration.',
            'composition' => 'Deliberate asymmetry and protest energy with faces remaining clear focal anchors.',
            'mood' => 'Defiant, urgent, handmade, confrontational, and alive.',
            'atmosphere' => 'Street-level immediacy and tactile analog imperfection.',
            'detail' => 'Strategic face clarity against rough surrounding reproduction.',
            'influence' => 'DIY zines, agitprop collage, xerography, and underground print culture.',
            'typography' => 'Use torn shapes instead of words unless original text is explicitly permitted.',
            'special' => 'Keep two identities separate even when collage layers overlap.',
            'avoid' => 'Clean gradients, corporate polish, readable copyrighted fragments, band logos.',
        ],
        'synthpop_1980s_neon_airbrush' => [
            'style' => 'Neon synth dream with polished 1980s airbrush atmosphere.',
            'medium' => 'Chrome airbrush, soft-focus film, gradient illustration, subtle VHS haze.',
            'color' => 'Magenta, cyan, electric blue, violet, black, and selective warm skin light.',
            'lighting' => 'Neon reflections, laser haze, colored rim light, luminous horizon glow.',
            'surface' => 'Chrome, smoked glass, satin, wet pavement, soft grid reflections.',
            'motion' => 'Laser beams, drifting haze, windblown clothing, light trails.',
            'composition' => 'Retro geometric depth with strong protagonists, horizon perspective, and controlled symmetry.',
            'mood' => 'Romantic, nocturnal, futuristic, nostalgic, and exhilarating.',
            'atmosphere' => 'VHS softness, bloom, faint scan texture, and cinematic night air.',
            'detail' => 'Faces remain naturally rendered against stylized luminous materials.',
            'influence' => '1980s airbrush illustration, synth-era lighting, and retro-futurist cinema.',
            'typography' => 'No retro title treatment unless original text is explicitly permitted.',
            'special' => 'Avoid turning the people into chrome mannequins; protect skin and identity.',
            'avoid' => 'Copied album layouts, desaturated realism, excessive grids, plastic faces.',
        ],
        'cyberpunk_neon_noir' => [
            'style' => 'Neon noir cinema with human emotion leading the technology.',
            'medium' => 'High-end digital matte painting with photographic rain, fog, and practical neon.',
            'color' => 'Cyan, magenta, violet, amber, wet black, and believable skin tones.',
            'lighting' => 'Colored rim light, reflected signage glow without readable brands, volumetric haze.',
            'surface' => 'Wet asphalt, glass, worn metal, fabric, condensation, restrained holographic light.',
            'motion' => 'Rain streaks, moving crowds as anonymous atmosphere, steam, fabric, distant light trails.',
            'composition' => 'Layered city depth, strong foreground figures, receding architecture, noir negative space.',
            'mood' => 'Intimate, dangerous, yearning, mysterious, and emotionally grounded.',
            'atmosphere' => 'Dense rain and haze sculpted by practical light.',
            'detail' => 'Faces and hands precise; technology supports rather than consumes the scene.',
            'influence' => 'Neon-noir cinematography, speculative urban design, and rain-soaked street photography.',
            'typography' => 'Environmental marks must be invented and unreadable unless original text is permitted.',
            'special' => 'Keep protagonists human, recognizable, and dramatically lit.',
            'avoid' => 'Over-mechanized armor, cluttered HUD overlays, copied franchises, brand signs.',
        ],
        'dreamcore' => [
            'style' => 'Liminal dream world with emotional symbolism and recognizable protagonists.',
            'medium' => 'Diffused digital matte painting blended with analog-photo softness and subtle decay.',
            'color' => 'Pale pastels, twilight blue, faded cream, uncanny fluorescent accents.',
            'lighting' => 'Nostalgic ambient glow, fluorescent pools, soft impossible daylight.',
            'surface' => 'Tile, carpet, clouds, fog, faded wallpaper, water, and quiet reflective planes.',
            'motion' => 'Suspended stillness, slow drift, distant curtains, floating dust, gentle water.',
            'composition' => 'Strong vanishing points, uncanny scale, spacious framing, people as emotional anchors.',
            'mood' => 'Nostalgic, uncanny, tender, lonely, peaceful, and quietly surreal.',
            'atmosphere' => 'Memory-like haze and ambiguous transitions between interior and exterior.',
            'detail' => 'Selective identity clarity surrounded by softly unresolved space.',
            'influence' => 'Liminal photography, surreal cinema, memory imagery, and analog domestic textures.',
            'typography' => 'No text unless it is original and deliberately requested.',
            'special' => 'Surrealism should deepen the emotional meaning, not become random object clutter.',
            'avoid' => 'Busy realism, horror clichés, hard digital edges, nonsensical extra figures.',
        ],
        'collage_surrealism' => [
            'style' => 'Surreal story collage with dimensional paper craft and coherent emotional symbolism.',
            'medium' => 'Vintage photographic cutouts, painted transitions, paper shadows, print texture.',
            'color' => 'Muted sepia and paper neutrals with turquoise, crimson, or cobalt focal accents.',
            'lighting' => 'Deliberately unreal composite light unified by soft edge shadow and vignette.',
            'surface' => 'Cut paper, deckled edges, glue marks, paint, halftone, layered depth.',
            'motion' => 'Floating fragments, scale shifts, unfolding paper, and controlled visual transformation.',
            'composition' => 'Unexpected juxtaposition organized around one readable narrative focal point.',
            'mood' => 'Poetic, uncanny, witty, nostalgic, and emotionally layered.',
            'atmosphere' => 'Handmade dream logic with believable tactile depth.',
            'detail' => 'Portrait faces remain coherent photographs or carefully unified painted cutouts.',
            'influence' => 'Surrealist assemblage, editorial collage, theater maquettes, and analog printmaking.',
            'typography' => 'No found printed words; use blank paper forms unless original text is permitted.',
            'special' => 'Unify disparate materials with consistent shadows and color relationships.',
            'avoid' => 'Random object piles, flat digital stickers, copied magazine text, broken facial anatomy.',
        ],
        'gothic_darkwave' => [
            'style' => 'Gothic romance with elegant darkness, human intimacy, and cinematic scale.',
            'medium' => 'Luminous oil-dark matte painting with refined portrait detail.',
            'color' => 'Deep crimson, violet, blue-black, silver, aged ivory, restrained candle gold.',
            'lighting' => 'Candlelit chiaroscuro, moonlit mist, narrow rays, silver rim light.',
            'surface' => 'Velvet, marble, lace, iron, rain-dark stone, old wood, translucent fabric.',
            'motion' => 'Slow drifting veils, rain, smoke, falling petals, and expressive restrained gesture.',
            'composition' => 'Mournful elegance, cathedral depth, strong silhouettes, intimate focal grouping.',
            'mood' => 'Romantic, haunted, solemn, devoted, mysterious, and beautiful rather than horrific.',
            'atmosphere' => 'Mist, candle smoke, moonlight, cavernous architectural air.',
            'detail' => 'Faces and eyes carry the emotion; ornate detail falls away from the focal plane.',
            'influence' => 'Gothic revival architecture, romantic painting, dark fashion editorial, and nocturnal cinema.',
            'typography' => 'No gothic title lettering unless original text is explicitly permitted.',
            'special' => 'Keep darkness luminous enough that both faces remain readable.',
            'avoid' => 'Gore, monster clichés, modern neon, comic-book contrast, copied gothic brands.',
        ],
        'fantasy_epic_illustration' => [
            'style' => 'Epic fantasy illustration with adventurous scale and emotionally grounded protagonists.',
            'medium' => 'Painterly digital illustration with oil-like surfaces and classic matte-painting depth.',
            'color' => 'Royal gold, sapphire, crimson, forest green, stone neutrals, atmospheric blue distance.',
            'lighting' => 'God rays, storm breaks, fire or magical ambience used as motivated cinematic light.',
            'surface' => 'Fabric, weathered armor without logos, stone, wood, water, clouds, foliage.',
            'motion' => 'Heroic movement, wind, banners without symbols, weather, creatures or landscape forces.',
            'composition' => 'Epic depth hierarchy with protagonists clearly dominant and environment revealing scale.',
            'mood' => 'Adventurous, mythic, courageous, romantic, and awe-filled.',
            'atmosphere' => 'Layered weather, distant terrain, volumetric light, and environmental storytelling.',
            'detail' => 'Poster-scale detail with especially strong faces, hands, costume materials, and foreground props.',
            'influence' => 'Classic adventure illustration, historical landscape painting, and modern fantasy cinema.',
            'typography' => 'No title, runes, heraldry, or readable marks unless entirely original and permitted.',
            'special' => 'Create a new world and event, never a recognizable franchise scene.',
            'avoid' => 'Flat cartoon rendering, generic character lineup, copied costumes, franchise iconography.',
        ],
    ];

    /** @return array<string, string> */
    public static function forKey(string $key, string $fallbackName = 'Cinematic Realism'): array
    {
        return self::MAPS[$key] ?? [
            'style' => $fallbackName . ' as the dominant, coherent visual treatment.',
            'medium' => 'Premium narrative artwork with a unified finish.',
            'color' => 'A controlled palette derived from the Song DNA.',
            'lighting' => 'Motivated cinematic light with dimensional shadow and readable faces.',
            'surface' => 'Tactile, believable materials appropriate to the selected world.',
            'motion' => 'Natural gesture and environmental movement.',
            'composition' => 'Clear focal hierarchy with foreground, middle ground, and background.',
            'mood' => 'Emotionally faithful to the approved Song DNA.',
            'atmosphere' => 'Depth, air, weather, and environmental storytelling.',
            'detail' => 'Highest detail on identities and the emotional focal point.',
            'influence' => 'General craft traditions and cinematic visual language.',
            'typography' => 'Only original permitted text; otherwise none.',
            'special' => 'Keep the final image cohesive and instantly readable.',
            'avoid' => 'Generic posing, flat backgrounds, copied promotional imagery, logos, and watermarks.',
        ];
    }

    /** @param array<string, string> $map */
    public static function compile(array $map): string
    {
        $labels = [
            'style' => 'STYLE', 'medium' => 'MEDIUM', 'color' => 'COLOR', 'lighting' => 'LIGHTING',
            'surface' => 'SURFACE', 'motion' => 'MOTION', 'composition' => 'COMPOSITION',
            'mood' => 'MOOD', 'atmosphere' => 'ATMOSPHERE', 'detail' => 'DETAIL',
            'influence' => 'INFLUENCE', 'typography' => 'TYPOGRAPHY', 'special' => 'SPECIAL', 'avoid' => 'AVOID',
        ];
        $lines = [];
        foreach ($labels as $key => $label) {
            if (($map[$key] ?? '') !== '') {
                $lines[] = $label . ': ' . $map[$key];
            }
        }
        return implode("\n", $lines);
    }
}
