<?php
declare(strict_types=1);
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; worker-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'");
header('Referrer-Policy: strict-origin-when-cross-origin');
header('X-Content-Type-Options: nosniff');
header('Cache-Control: no-store');
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#14331d"><title>FirstRuck · A little weight goes a long way</title><link rel="stylesheet" href="asset.php?file=maplibre.css"><link rel="stylesheet" href="asset.php?file=experience.css&amp;v=3"></head>
<body class="web-app" data-asset-base="asset.php?file=" data-api="mapping.php"><a class="skip" href="#screen">Skip to experience</a><aside class="studio"><a class="wordmark" href="./"><img src="asset.php?file=firstruck-mark.svg" alt="">FirstRuck<span>FIELD NOTES / 02</span></a><div><p class="eyebrow">THE FIRST MONTH, REIMAGINED</p><h1>A little weight.<br>A world outside.</h1><p class="studio-copy">A calmer start. A companion for the journey.<br>Something worth coming back to.</p></div><nav aria-label="Design review"><button data-jump="welcome">01 / The beginning</button><button data-jump="meet-kip">02 / Meet your companion</button><button data-jump="routes">03 / Plan a route</button><button data-jump="paywall">04 / Membership</button><button data-jump="today">05 / Inside FirstRuck</button><button data-jump="journal">06 / Your field journal</button></nav><p class="review-note">Interactive design preview · Routes are examples.<br>Purchases and community publishing are not connected.</p></aside><div class="device"><div class="device-top"><span>9:41</span><span class="island"></span><span aria-hidden="true">▮▮▮  ▰</span></div><main id="screen" tabindex="-1"></main><div class="device-bottom"></div></div><aside class="annotation"><p class="eyebrow" id="review-chapter">THE BEGINNING</p><h2 id="review-title">An invitation, not a questionnaire.</h2><p id="review-copy">Start with the feeling of getting outside. Then ask only what changes the plan.</p><div class="annotation-line"></div><p class="eyebrow">DESIGN DIRECTION</p><p>Forest. Field paper. A single orange thread.</p><p>Real-world photography meets a quietly playful companion.</p><button class="text-button" id="restart">Restart onboarding</button></aside><div id="status" class="sr-only" role="status"></div><script src="asset.php?file=maplibre.js"></script><script src="asset.php?file=model.js"></script><script src="asset.php?file=screens.js"></script><script src="asset.php?file=flow.js&amp;v=3"></script><script src="asset.php?file=storage.js"></script><script src="asset.php?file=mapping.js"></script><script src="asset.php?file=experience.js&amp;v=3"></script></body></html>
